### ISSUE TITLE
glove 840B - rerun

### ISSUE THREAD

**Issue by kudkudak** [kudkudak/word-embeddings-benchmarks#29]
Wiki page (https://github.com/kudkudak/word-embeddings-benchmarks/wiki) reported very bad results for 840B glove, rerun

**Comment by rspeer** [comment]
I have also gotten very bad results from unmodified 840B GloVe. For example, RW=.146. I suspect you did it correctly.

840B contains some useful data, but there is something very wrong with its scaling, especially in the long tail of its vocabulary. You have to bring your own normalization and regularization. We managed to get it to RW=.503, MEN=.840, WS353=.798, which would be the best thing on the table (but only because you don't have ConceptNet Numberbatch in the table).

We examined this in an unpublished paper that was one of the steps on the way to making Numberbatch: https://pdfs.semanticscholar.org/6bc3/ef19eec3ebbdb2ad81231062090e60c38c52.pdf

You may want to look at the current code for how ConceptNet renormalizes GloVe: https://github.com/commonsense/conceptnet5/blob/master/conceptnet5/vectors/formats.py#L74

**Comment by kudkudak** [comment]
This also explains why I saw good numbers when using supervised evaluation models like in my https://arxiv.org/abs/1702.02170. Thanks a lot for your input :) !

**Comment by kudkudak** [comment]
Oh - and we are working on adding Numberbatch to the table ;)
