### ISSUE TITLE
There is no Fasttext in the wiki's table

### ISSUE THREAD

**Issue by DonaldTsang** [kudkudak/word-embeddings-benchmarks#52]
See https://github.com/kudkudak/word-embeddings-benchmarks/wiki

**Comment by kudkudak** [comment]
We are not actively maintaining this page, because evaluating word embeddings requires more care, e.g. making sure vocabularies are shared, or that all embeddings were trained on the same corpora. As such, I am closing this issue, but in case you have scores for FastText, we will be happy to add them.
